application: dtcgithubbot
version: 5
runtime: python
api_version: 1

inbound_services:
- xmpp_message
handlers:
- url: /_ah/xmpp/message/chat/.*
  script: XmppHandler.py
- url: /post-receive
  script: PostReceiveHandler.py
- url: /post-receive/.*
  script: PostReceiveHandler.py
- url: /changelog/.*
  script: ChangeLogHandler.py
builtins:
- datastore_admin: on
